import { ArrowRight, CalendarDays, Check, ChevronRight, Compass, MapPin, ShieldCheck, Sparkles, Star, Waves } from 'lucide-react';
import { useCompanions } from '@/hooks/useCompanions';
import { navigate } from '@/lib/router';
import { CompanionCard } from '@/components/CompanionCard';

const benefits = [
  { icon: ShieldCheck, title: 'Vetted locally', text: 'Real people, reviewed for respectful and safe experiences.' },
  { icon: CalendarDays, title: 'Easy to arrange', text: 'Choose your date, duration, and meeting point in minutes.' },
  { icon: Waves, title: 'Made for Diani', text: 'Beach days, boat trips, sunset dinners, and more.' },
];

export function HomePage() {
  const { companions, loading, error } = useCompanions();
  return <main>
    <section className="relative min-h-[720px] overflow-hidden border-b border-white/10 bg-ocean-950">
      <img src="https://images.pexels.com/photos/1476356/pexels-photo-1476356.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" alt="Diani Beach at the coast" className="absolute inset-0 h-full w-full object-cover opacity-40" />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_35%,rgba(42,157,152,.28),transparent_35%),linear-gradient(90deg,#061519_10%,rgba(6,21,25,.88)_42%,rgba(6,21,25,.28))]" />
      <div className="relative mx-auto flex min-h-[720px] max-w-7xl items-center px-5 pb-16 pt-28 lg:px-8"><div className="max-w-2xl animate-fade-up"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-ocean-300/30 bg-ocean-900/70 px-3.5 py-2 text-xs font-semibold uppercase tracking-[0.16em] text-ocean-200 backdrop-blur"><Sparkles size={14} className="text-sand-300" /> Your Diani, your way</div><h1 className="font-display text-5xl font-semibold leading-[1.04] tracking-tight text-white sm:text-7xl">Good company<br /><span className="text-ocean-300">comes naturally.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-white/70 sm:text-lg">Meet vetted local companions who know Diani inside out — for a beach day, a sunset dinner, or wherever the coast takes you.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={() => navigate('/browse')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-ocean-400 px-5 py-3.5 text-sm font-bold text-ocean-950 shadow-xl shadow-ocean-500/20 transition hover:bg-ocean-300">Explore companions <ArrowRight size={17} /></button><button onClick={() => navigate('/about')} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/5 px-5 py-3.5 text-sm font-semibold text-white backdrop-blur transition hover:bg-white/10">How it works <ChevronRight size={16} /></button></div><div className="mt-10 flex items-center gap-5 text-sm text-white/55"><div className="flex -space-x-2"><img className="h-8 w-8 rounded-full border-2 border-ocean-950 object-cover" src="https://images.pexels.com/photos/27742237/pexels-photo-27742237.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" alt="" /><img className="h-8 w-8 rounded-full border-2 border-ocean-950 object-cover" src="https://images.pexels.com/photos/27965323/pexels-photo-27965323.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" alt="" /><img className="h-8 w-8 rounded-full border-2 border-ocean-950 object-cover" src="https://images.pexels.com/photos/27742230/pexels-photo-27742230.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" alt="" /></div><span>Trusted by guests from around the world</span></div></div></div>
    </section>
    <section className="border-b border-white/10 bg-ocean-900/45 px-5 py-10 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3">{benefits.map(({ icon: Icon, title, text }) => <div key={title} className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-ocean-500/15 text-ocean-300"><Icon size={21} /></span><div><h3 className="font-semibold text-white">{title}</h3><p className="mt-1 text-sm leading-6 text-white/50">{text}</p></div></div>)}</div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="mb-8 flex items-end justify-between"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-ocean-300">Curated for you</p><h2 className="font-display text-4xl font-semibold text-white sm:text-5xl">Meet the locals</h2></div><button onClick={() => navigate('/browse')} className="hidden items-center gap-2 text-sm font-semibold text-ocean-300 transition hover:text-ocean-200 sm:flex">View all <ArrowRight size={16} /></button></div>{loading ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(i => <div key={i} className="skeleton aspect-[4/5] rounded-2xl" />)}</div> : error ? <div className="rounded-2xl border border-coral-500/30 bg-coral-500/10 p-6 text-white/75">We couldn’t load companions right now. Please try again.</div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{companions.slice(0, 3).map((c, i) => <CompanionCard key={c.id} companion={c} index={i} />)}</div>}<button onClick={() => navigate('/browse')} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border border-white/15 py-3 text-sm font-semibold text-white/75 hover:bg-white/6 sm:hidden">View all companions <ArrowRight size={16} /></button></section>
    <section className="relative overflow-hidden border-y border-white/10 bg-ocean-800/35 px-5 py-20 lg:px-8"><div className="absolute -right-36 -top-48 h-96 w-96 rounded-full bg-ocean-400/10 blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-10 md:grid-cols-[1fr_auto]"><div><p className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-sand-300">The Diani edit</p><h2 className="max-w-xl font-display text-4xl font-semibold leading-tight text-white sm:text-5xl">One coastline.<br />Endless ways to spend it.</h2><p className="mt-5 max-w-lg leading-7 text-white/60">From first light on the water to the last song at the beach bar, find someone who fits the mood.</p></div><button onClick={() => navigate('/browse')} className="inline-flex items-center justify-center gap-3 rounded-xl bg-sand-300 px-6 py-4 text-sm font-bold text-ocean-950 transition hover:bg-sand-200">Find your kind of day <ArrowRight size={18} /></button></div></section>
  </main>;
}
